// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'My Terrible Python Projects',
      items: [
        'tutorial-basic/lggp',
        'tutorial-basic/qgp',
      ],
    },

    {
      type: 'category',
      label: 'Other Compiled Projects!',
      items: [
        'other-comps/1compinfo',
        'other-comps/winutils',
        'other-comps/zed',
      ],
    },
  ],
  
  notesSidebar: [
    'notes',
    {
      type: 'category',
      label: 'Science Notes',
      items: [
        'sci/phy',
        'sci/chem',
        'sci/bio',
      ],
    },
    /*{
      type: 'category',
      label: 'Social Science Notes',
      items: [

      ],
    },
    {
      type: 'category',
      label: 'Math Notes',
      items: [

      ],
    },
    {
      type: 'category',
      label: 'English Notes',
      items: [

      ],
    },*/
  ],

};

export default sidebars;
